name: 'zoom'
version: '1.0.0'
config-version: 2

profile: 'Analytics'

model-paths: ["models"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]

target-path: "target"
clean-targets: ["target"]

vars:
  source_schema: 'RAW'
  target_schema: 'BRONZE'

models:
  zoom:
    bronze:
      +materialized: table
      +schema: bronze
      +pre-hook:
        - "{{ audit_start_hook() }}"
      +post-hook:
        - "{{ audit_end_hook() }}"
