name: 'zoom'
version: '1.0.0'
config-version: 2

profile: 'Analytics'

model-paths: ["models"]
macro-paths: ["macros"]

target-path: "target"
clean-targets: ["target"]

models:
  zoom:
    bronze:
      +materialized: table
      +schema: bronze

vars:
  source_system: 'ZOOM_PLATFORM'
