name: 'zoom'
version: '1.0.0'
config-version: 2

profile: 'Analytics'

model-paths: ["models"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]

target-path: "target"
clean-targets: ["target"]

models:
  zoom:
    bronze:
      +materialized: table
      +schema: bronze
      # Ensure audit_log runs first
      bz_audit_log:
        +materialized: table
        +schema: bronze
        +tags: ['audit']
