name: 'Analytics'
version: '1.0.0'
config-version: 2

profile: 'Analytics'

model-paths: ["models"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]

target-path: "target"
clean-targets: ["target"]

models:
  Analytics:
    bronze:
      +materialized: table
      +schema: bronze
      +pre-hook:
        - "{{ logging.log_model_start() }}"
      +post-hook:
        - "{{ logging.log_model_end() }}"
