name: 'zoom_analytics'
version: '1.0.0'
config-version: 2

profile: 'Analytics'

model-paths: ["models"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]

target-path: "target"
clean-targets: ["target"]

models:
  zoom_analytics:
    bronze:
      +materialized: table
      +schema: bronze
      audit:
        +schema: bronze
        +tags: ["audit"]
