version: 2

sources:
  - name: raw
    schema: raw
    tables:
      - name: users
        description: Raw users data from Zoom platform
        columns:
          - name: user_id
            description: Unique identifier for a user
          - name: user_name
            description: Name of the user
          - name: email
            description: Email address of the user
          - name: company
            description: Company the user belongs to
          - name: plan_type
            description: Type of plan the user has
          - name: load_timestamp
            description: Timestamp when the record was loaded
          - name: update_timestamp
            description: Timestamp when the record was last updated
          - name: source_system
            description: Source system of the data

      - name: meetings
        description: Raw meetings data from Zoom platform
        columns:
          - name: meeting_id
            description: Unique identifier for a meeting
          - name: host_id
            description: ID of the user hosting the meeting
          - name: meeting_topic
            description: Topic of the meeting
          - name: start_time
            description: Start time of the meeting
          - name: end_time
            description: End time of the meeting
          - name: duration_minutes
            description: Duration of the meeting in minutes
          - name: load_timestamp
            description: Timestamp when the record was loaded
          - name: update_timestamp
            description: Timestamp when the record was last updated
          - name: source_system
            description: Source system of the data

      - name: participants
        description: Raw participants data from Zoom platform
        columns:
          - name: participant_id
            description: Unique identifier for a participant
          - name: meeting_id
            description: ID of the meeting
          - name: user_id
            description: ID of the user participating
          - name: join_time
            description: Time when the participant joined the meeting
          - name: leave_time
            description: Time when the participant left the meeting
          - name: load_timestamp
            description: Timestamp when the record was loaded
          - name: update_timestamp
            description: Timestamp when the record was last updated
          - name: source_system
            description: Source system of the data

      - name: feature_usage
        description: Raw feature usage data from Zoom platform
        columns:
          - name: usage_id
            description: Unique identifier for a feature usage record
          - name: meeting_id
            description: ID of the meeting
          - name: feature_name
            description: Name of the feature used
          - name: usage_count
            description: Count of feature usage
          - name: usage_date
            description: Date of feature usage
          - name: load_timestamp
            description: Timestamp when the record was loaded
          - name: update_timestamp
            description: Timestamp when the record was last updated
          - name: source_system
            description: Source system of the data

      - name: webinars
        description: Raw webinars data from Zoom platform
        columns:
          - name: webinar_id
            description: Unique identifier for a webinar
          - name: host_id
            description: ID of the user hosting the webinar
          - name: webinar_topic
            description: Topic of the webinar
          - name: start_time
            description: Start time of the webinar
          - name: end_time
            description: End time of the webinar
          - name: registrants
            description: Number of registrants for the webinar
          - name: load_timestamp
            description: Timestamp when the record was loaded
          - name: update_timestamp
            description: Timestamp when the record was last updated
          - name: source_system
            description: Source system of the data

      - name: support_tickets
        description: Raw support tickets data from Zoom platform
        columns:
          - name: ticket_id
            description: Unique identifier for a support ticket
          - name: user_id
            description: ID of the user who created the ticket
          - name: ticket_type
            description: Type of the support ticket
          - name: resolution_status
            description: Status of ticket resolution
          - name: open_date
            description: Date when the ticket was opened
          - name: load_timestamp
            description: Timestamp when the record was loaded
          - name: update_timestamp
            description: Timestamp when the record was last updated
          - name: source_system
            description: Source system of the data

      - name: licenses
        description: Raw licenses data from Zoom platform
        columns:
          - name: license_id
            description: Unique identifier for a license
          - name: license_type
            description: Type of license
          - name: assigned_to_user_id
            description: ID of the user the license is assigned to
          - name: start_date
            description: Start date of the license
          - name: end_date
            description: End date of the license
          - name: load_timestamp
            description: Timestamp when the record was loaded
          - name: update_timestamp
            description: Timestamp when the record was last updated
          - name: source_system
            description: Source system of the data

      - name: billing_events
        description: Raw billing events data from Zoom platform
        columns:
          - name: event_id
            description: Unique identifier for a billing event
          - name: user_id
            description: ID of the user associated with the billing event
          - name: event_type
            description: Type of billing event
          - name: amount
            description: Amount associated with the billing event
          - name: event_date
            description: Date of the billing event
          - name: load_timestamp
            description: Timestamp when the record was loaded
          - name: update_timestamp
            description: Timestamp when the record was last updated
          - name: source_system
            description: Source system of the data

models:
  - name: bz_audit_log
    description: Audit log for bronze layer transformations
    columns:
      - name: record_id
        description: Unique identifier for the audit record
      - name: source_table
        description: Source table being processed
      - name: load_timestamp
        description: Timestamp when the processing occurred
      - name: processed_by
        description: User or process that performed the processing
      - name: processing_time
        description: Time taken for processing in seconds
      - name: status
        description: Status of the processing (success/failure)

  - name: bz_users
    description: Bronze layer users data
    columns:
      - name: user_id
        description: Unique identifier for a user
      - name: user_name
        description: Name of the user
      - name: email
        description: Email address of the user
      - name: company
        description: Company the user belongs to
      - name: plan_type
        description: Type of plan the user has
      - name: load_timestamp
        description: Timestamp when the record was loaded
      - name: update_timestamp
        description: Timestamp when the record was last updated
      - name: source_system
        description: Source system of the data

  - name: bz_meetings
    description: Bronze layer meetings data
    columns:
      - name: meeting_id
        description: Unique identifier for a meeting
      - name: host_id
        description: ID of the user hosting the meeting
      - name: meeting_topic
        description: Topic of the meeting
      - name: start_time
        description: Start time of the meeting
      - name: end_time
        description: End time of the meeting
      - name: duration_minutes
        description: Duration of the meeting in minutes
      - name: load_timestamp
        description: Timestamp when the record was loaded
      - name: update_timestamp
        description: Timestamp when the record was last updated
      - name: source_system
        description: Source system of the data

  - name: bz_participants
    description: Bronze layer participants data
    columns:
      - name: participant_id
        description: Unique identifier for a participant
      - name: meeting_id
        description: ID of the meeting
      - name: user_id
        description: ID of the user participating
      - name: join_time
        description: Time when the participant joined the meeting
      - name: leave_time
        description: Time when the participant left the meeting
      - name: load_timestamp
        description: Timestamp when the record was loaded
      - name: update_timestamp
        description: Timestamp when the record was last updated
      - name: source_system
        description: Source system of the data

  - name: bz_feature_usage
    description: Bronze layer feature usage data
    columns:
      - name: usage_id
        description: Unique identifier for a feature usage record
      - name: meeting_id
        description: ID of the meeting
      - name: feature_name
        description: Name of the feature used
      - name: usage_count
        description: Count of feature usage
      - name: usage_date
        description: Date of feature usage
      - name: load_timestamp
        description: Timestamp when the record was loaded
      - name: update_timestamp
        description: Timestamp when the record was last updated
      - name: source_system
        description: Source system of the data

  - name: bz_webinars
    description: Bronze layer webinars data
    columns:
      - name: webinar_id
        description: Unique identifier for a webinar
      - name: host_id
        description: ID of the user hosting the webinar
      - name: webinar_topic
        description: Topic of the webinar
      - name: start_time
        description: Start time of the webinar
      - name: end_time
        description: End time of the webinar
      - name: registrants
        description: Number of registrants for the webinar
      - name: load_timestamp
        description: Timestamp when the record was loaded
      - name: update_timestamp
        description: Timestamp when the record was last updated
      - name: source_system
        description: Source system of the data

  - name: bz_support_tickets
    description: Bronze layer support tickets data
    columns:
      - name: ticket_id
        description: Unique identifier for a support ticket
      - name: user_id
        description: ID of the user who created the ticket
      - name: ticket_type
        description: Type of the support ticket
      - name: resolution_status
        description: Status of ticket resolution
      - name: open_date
        description: Date when the ticket was opened
      - name: load_timestamp
        description: Timestamp when the record was loaded
      - name: update_timestamp
        description: Timestamp when the record was last updated
      - name: source_system
        description: Source system of the data

  - name: bz_licenses
    description: Bronze layer licenses data
    columns:
      - name: license_id
        description: Unique identifier for a license
      - name: license_type
        description: Type of license
      - name: assigned_to_user_id
        description: ID of the user the license is assigned to
      - name: start_date
        description: Start date of the license
      - name: end_date
        description: End date of the license
      - name: load_timestamp
        description: Timestamp when the record was loaded
      - name: update_timestamp
        description: Timestamp when the record was last updated
      - name: source_system
        description: Source system of the data

  - name: bz_billing_events
    description: Bronze layer billing events data
    columns:
      - name: event_id
        description: Unique identifier for a billing event
      - name: user_id
        description: ID of the user associated with the billing event
      - name: event_type
        description: Type of billing event
      - name: amount
        description: Amount associated with the billing event
      - name: event_date
        description: Date of the billing event
      - name: load_timestamp
        description: Timestamp when the record was loaded
      - name: update_timestamp
        description: Timestamp when the record was last updated
      - name: source_system
        description: Source system of the data
