version: 2

models:
  - name: bz_audit_log
    description: "Audit log for tracking bronze layer data processing"
    columns:
      - name: record_id
        description: "Unique identifier for the audit record"
        tests:
          - not_null
          - unique
      - name: source_table
        description: "Source table being processed"
        tests:
          - not_null
      - name: load_timestamp
        description: "Timestamp when the data was loaded"
        tests:
          - not_null
      - name: processed_by
        description: "User or process that processed the data"
      - name: processing_time
        description: "Time taken to process the data in seconds"
      - name: status
        description: "Status of the processing (success/failure)"
        tests:
          - not_null

  - name: bz_users
    description: "Bronze layer for user data"
    columns:
      - name: user_id
        description: "Unique identifier for the user"
        tests:
          - not_null
          - unique
      - name: user_name
        description: "Name of the user"
      - name: email
        description: "Email address of the user"
      - name: company
        description: "Company the user belongs to"
      - name: plan_type
        description: "Type of plan the user has"
      - name: load_timestamp
        description: "Timestamp when the data was loaded"
        tests:
          - not_null
      - name: update_timestamp
        description: "Timestamp when the data was last updated"
        tests:
          - not_null
      - name: source_system
        description: "Source system of the data"
        tests:
          - not_null

  - name: bz_meetings
    description: "Bronze layer for meeting data"
    columns:
      - name: meeting_id
        description: "Unique identifier for the meeting"
        tests:
          - not_null
          - unique
      - name: host_id
        description: "ID of the meeting host"
        tests:
          - not_null
      - name: meeting_topic
        description: "Topic of the meeting"
      - name: start_time
        description: "Start time of the meeting"
      - name: end_time
        description: "End time of the meeting"
      - name: duration_minutes
        description: "Duration of the meeting in minutes"
      - name: load_timestamp
        description: "Timestamp when the data was loaded"
        tests:
          - not_null
      - name: update_timestamp
        description: "Timestamp when the data was last updated"
        tests:
          - not_null
      - name: source_system
        description: "Source system of the data"
        tests:
          - not_null

  - name: bz_participants
    description: "Bronze layer for participant data"
    columns:
      - name: participant_id
        description: "Unique identifier for the participant"
        tests:
          - not_null
          - unique
      - name: meeting_id
        description: "ID of the meeting"
        tests:
          - not_null
      - name: user_id
        description: "ID of the user"
      - name: join_time
        description: "Time when the participant joined"
      - name: leave_time
        description: "Time when the participant left"
      - name: load_timestamp
        description: "Timestamp when the data was loaded"
        tests:
          - not_null
      - name: update_timestamp
        description: "Timestamp when the data was last updated"
        tests:
          - not_null
      - name: source_system
        description: "Source system of the data"
        tests:
          - not_null

  - name: bz_feature_usage
    description: "Bronze layer for feature usage data"
    columns:
      - name: usage_id
        description: "Unique identifier for the usage record"
        tests:
          - not_null
          - unique
      - name: meeting_id
        description: "ID of the meeting"
        tests:
          - not_null
      - name: feature_name
        description: "Name of the feature used"
        tests:
          - not_null
      - name: usage_count
        description: "Count of feature usage"
      - name: usage_date
        description: "Date of feature usage"
      - name: load_timestamp
        description: "Timestamp when the data was loaded"
        tests:
          - not_null
      - name: update_timestamp
        description: "Timestamp when the data was last updated"
        tests:
          - not_null
      - name: source_system
        description: "Source system of the data"
        tests:
          - not_null

  - name: bz_webinars
    description: "Bronze layer for webinar data"
    columns:
      - name: webinar_id
        description: "Unique identifier for the webinar"
        tests:
          - not_null
          - unique
      - name: host_id
        description: "ID of the webinar host"
        tests:
          - not_null
      - name: webinar_topic
        description: "Topic of the webinar"
      - name: start_time
        description: "Start time of the webinar"
      - name: end_time
        description: "End time of the webinar"
      - name: registrants
        description: "Number of registrants for the webinar"
      - name: load_timestamp
        description: "Timestamp when the data was loaded"
        tests:
          - not_null
      - name: update_timestamp
        description: "Timestamp when the data was last updated"
        tests:
          - not_null
      - name: source_system
        description: "Source system of the data"
        tests:
          - not_null

  - name: bz_support_tickets
    description: "Bronze layer for support ticket data"
    columns:
      - name: ticket_id
        description: "Unique identifier for the support ticket"
        tests:
          - not_null
          - unique
      - name: user_id
        description: "ID of the user who created the ticket"
        tests:
          - not_null
      - name: ticket_type
        description: "Type of support ticket"
      - name: resolution_status
        description: "Status of ticket resolution"
      - name: open_date
        description: "Date when the ticket was opened"
      - name: load_timestamp
        description: "Timestamp when the data was loaded"
        tests:
          - not_null
      - name: update_timestamp
        description: "Timestamp when the data was last updated"
        tests:
          - not_null
      - name: source_system
        description: "Source system of the data"
        tests:
          - not_null

  - name: bz_licenses
    description: "Bronze layer for license data"
    columns:
      - name: license_id
        description: "Unique identifier for the license"
        tests:
          - not_null
          - unique
      - name: license_type
        description: "Type of license"
      - name: assigned_to_user_id
        description: "ID of the user the license is assigned to"
      - name: start_date
        description: "Start date of the license"
      - name: end_date
        description: "End date of the license"
      - name: load_timestamp
        description: "Timestamp when the data was loaded"
        tests:
          - not_null
      - name: update_timestamp
        description: "Timestamp when the data was last updated"
        tests:
          - not_null
      - name: source_system
        description: "Source system of the data"
        tests:
          - not_null

  - name: bz_billing_events
    description: "Bronze layer for billing event data"
    columns:
      - name: event_id
        description: "Unique identifier for the billing event"
        tests:
          - not_null
          - unique
      - name: user_id
        description: "ID of the user associated with the billing event"
        tests:
          - not_null
      - name: event_type
        description: "Type of billing event"
      - name: amount
        description: "Amount associated with the billing event"
      - name: event_date
        description: "Date of the billing event"
      - name: load_timestamp
        description: "Timestamp when the data was loaded"
        tests:
          - not_null
      - name: update_timestamp
        description: "Timestamp when the data was last updated"
        tests:
          - not_null
      - name: source_system
        description: "Source system of the data"
        tests:
          - not_null
