version: 2

sources:
  - name: raw
    database: raw
    schema: raw
    tables:
      - name: users
      - name: meetings
      - name: participants
      - name: feature_usage
      - name: webinars
      - name: support_tickets
      - name: licenses
      - name: billing_events

models:
  - name: bz_audit_log
    description: "Audit log for bronze layer transformations"
    columns:
      - name: record_id
        description: "Unique identifier for the audit record"
        tests:
          - unique
          - not_null
      - name: source_table
        description: "Name of the source table being processed"
      - name: load_timestamp
        description: "Timestamp when the processing started"
      - name: processed_by
        description: "User who processed the data"
      - name: processing_time
        description: "Time taken to process the data in seconds"
      - name: status
        description: "Status of the processing (STARTED, COMPLETED, FAILED)"

  - name: bz_users
    description: "Bronze layer for users data"
    columns:
      - name: user_id
        description: "Unique identifier for the user"
        tests:
          - unique
          - not_null
      - name: user_name
        description: "Name of the user"
      - name: email
        description: "Email address of the user"
      - name: company
        description: "Company the user belongs to"
      - name: plan_type
        description: "Type of plan the user has"
      - name: load_timestamp
        description: "Timestamp when the record was loaded"
      - name: update_timestamp
        description: "Timestamp when the record was last updated"
      - name: source_system
        description: "Source system the data was extracted from"
