version: 2

sources:
  - name: zoom
    description: "Raw data from Zoom platform"
    tables:
      - name: users
        description: "Raw user data from Zoom"
        columns:
          - name: user_id
            description: "Unique identifier for a user"
          - name: user_name
            description: "User's name"
          - name: email
            description: "User's email address"
          - name: company
            description: "User's company"
          - name: plan_type
            description: "User's subscription plan type"

      - name: meetings
        description: "Raw meeting data from Zoom"
        columns:
          - name: meeting_id
            description: "Unique identifier for a meeting"
          - name: host_id
            description: "ID of the user who hosted the meeting"
          - name: meeting_topic
            description: "Topic of the meeting"
          - name: start_time
            description: "Start time of the meeting"
          - name: end_time
            description: "End time of the meeting"
          - name: duration_minutes
            description: "Duration of the meeting in minutes"

      - name: participants
        description: "Raw participant data from Zoom meetings"
        columns:
          - name: participant_id
            description: "Unique identifier for a participant"
          - name: meeting_id
            description: "ID of the meeting the participant joined"
          - name: user_id
            description: "ID of the user who participated"
          - name: join_time
            description: "Time when participant joined the meeting"
          - name: leave_time
            description: "Time when participant left the meeting"

      - name: feature_usage
        description: "Raw feature usage data from Zoom"
        columns:
          - name: usage_id
            description: "Unique identifier for feature usage"
          - name: meeting_id
            description: "ID of the meeting where feature was used"
          - name: feature_name
            description: "Name of the feature used"
          - name: usage_count
            description: "Count of feature usage"
          - name: usage_date
            description: "Date when feature was used"

      - name: webinars
        description: "Raw webinar data from Zoom"
        columns:
          - name: webinar_id
            description: "Unique identifier for a webinar"
          - name: host_id
            description: "ID of the user who hosted the webinar"
          - name: webinar_topic
            description: "Topic of the webinar"
          - name: start_time
            description: "Start time of the webinar"
          - name: end_time
            description: "End time of the webinar"
          - name: registrants
            description: "Number of registrants for the webinar"

      - name: support_tickets
        description: "Raw support ticket data from Zoom"
        columns:
          - name: ticket_id
            description: "Unique identifier for a support ticket"
          - name: user_id
            description: "ID of the user who submitted the ticket"
          - name: ticket_type
            description: "Type of support ticket"
          - name: resolution_status
            description: "Current status of ticket resolution"
          - name: open_date
            description: "Date when ticket was opened"

      - name: licenses
        description: "Raw license data from Zoom"
        columns:
          - name: license_id
            description: "Unique identifier for a license"
          - name: license_type
            description: "Type of license"
          - name: assigned_to_user_id
            description: "ID of the user assigned to the license"
          - name: start_date
            description: "Start date of the license"
          - name: end_date
            description: "End date of the license"

      - name: billing_events
        description: "Raw billing event data from Zoom"
        columns:
          - name: event_id
            description: "Unique identifier for a billing event"
          - name: user_id
            description: "ID of the user associated with the billing event"
          - name: event_type
            description: "Type of billing event"
          - name: amount
            description: "Amount associated with the billing event"
          - name: event_date
            description: "Date of the billing event"

models:
  - name: bz_audit_log
    description: "Audit log for tracking bronze layer transformations"
    columns:
      - name: record_id
        description: "Unique identifier for the audit record"
      - name: source_table
        description: "Source table being processed"
      - name: load_timestamp
        description: "Timestamp when the data was loaded"
      - name: processed_by
        description: "User or process that processed the data"
      - name: processing_time
        description: "Time taken to process the data in seconds"
      - name: status
        description: "Status of the processing (success/failure)"

  - name: bz_users
    description: "Bronze layer for user data"
    columns:
      - name: user_id
        description: "Unique identifier for a user"
        tests:
          - unique
          - not_null
      - name: user_name
        description: "User's name"
      - name: email
        description: "User's email address"
      - name: company
        description: "User's company"
      - name: plan_type
        description: "User's subscription plan type"
      - name: load_timestamp
        description: "Timestamp when the data was loaded"
      - name: update_timestamp
        description: "Timestamp when the data was last updated"
      - name: source_system
        description: "Source system of the data"

  - name: bz_meetings
    description: "Bronze layer for meeting data"
    columns:
      - name: meeting_id
        description: "Unique identifier for a meeting"
        tests:
          - unique
          - not_null
      - name: host_id
        description: "ID of the user who hosted the meeting"
      - name: meeting_topic
        description: "Topic of the meeting"
      - name: start_time
        description: "Start time of the meeting"
      - name: end_time
        description: "End time of the meeting"
      - name: duration_minutes
        description: "Duration of the meeting in minutes"
      - name: load_timestamp
        description: "Timestamp when the data was loaded"
      - name: update_timestamp
        description: "Timestamp when the data was last updated"
      - name: source_system
        description: "Source system of the data"

  - name: bz_participants
    description: "Bronze layer for participant data"
    columns:
      - name: participant_id
        description: "Unique identifier for a participant"
        tests:
          - unique
          - not_null
      - name: meeting_id
        description: "ID of the meeting the participant joined"
      - name: user_id
        description: "ID of the user who participated"
      - name: join_time
        description: "Time when participant joined the meeting"
      - name: leave_time
        description: "Time when participant left the meeting"
      - name: load_timestamp
        description: "Timestamp when the data was loaded"
      - name: update_timestamp
        description: "Timestamp when the data was last updated"
      - name: source_system
        description: "Source system of the data"

  - name: bz_feature_usage
    description: "Bronze layer for feature usage data"
    columns:
      - name: usage_id
        description: "Unique identifier for feature usage"
        tests:
          - unique
          - not_null
      - name: meeting_id
        description: "ID of the meeting where feature was used"
      - name: feature_name
        description: "Name of the feature used"
      - name: usage_count
        description: "Count of feature usage"
      - name: usage_date
        description: "Date when feature was used"
      - name: load_timestamp
        description: "Timestamp when the data was loaded"
      - name: update_timestamp
        description: "Timestamp when the data was last updated"
      - name: source_system
        description: "Source system of the data"

  - name: bz_webinars
    description: "Bronze layer for webinar data"
    columns:
      - name: webinar_id
        description: "Unique identifier for a webinar"
        tests:
          - unique
          - not_null
      - name: host_id
        description: "ID of the user who hosted the webinar"
      - name: webinar_topic
        description: "Topic of the webinar"
      - name: start_time
        description: "Start time of the webinar"
      - name: end_time
        description: "End time of the webinar"
      - name: registrants
        description: "Number of registrants for the webinar"
      - name: load_timestamp
        description: "Timestamp when the data was loaded"
      - name: update_timestamp
        description: "Timestamp when the data was last updated"
      - name: source_system
        description: "Source system of the data"

  - name: bz_support_tickets
    description: "Bronze layer for support ticket data"
    columns:
      - name: ticket_id
        description: "Unique identifier for a support ticket"
        tests:
          - unique
          - not_null
      - name: user_id
        description: "ID of the user who submitted the ticket"
      - name: ticket_type
        description: "Type of support ticket"
      - name: resolution_status
        description: "Current status of ticket resolution"
      - name: open_date
        description: "Date when ticket was opened"
      - name: load_timestamp
        description: "Timestamp when the data was loaded"
      - name: update_timestamp
        description: "Timestamp when the data was last updated"
      - name: source_system
        description: "Source system of the data"

  - name: bz_licenses
    description: "Bronze layer for license data"
    columns:
      - name: license_id
        description: "Unique identifier for a license"
        tests:
          - unique
          - not_null
      - name: license_type
        description: "Type of license"
      - name: assigned_to_user_id
        description: "ID of the user assigned to the license"
      - name: start_date
        description: "Start date of the license"
      - name: end_date
        description: "End date of the license"
      - name: load_timestamp
        description: "Timestamp when the data was loaded"
      - name: update_timestamp
        description: "Timestamp when the data was last updated"
      - name: source_system
        description: "Source system of the data"

  - name: bz_billing_events
    description: "Bronze layer for billing event data"
    columns:
      - name: event_id
        description: "Unique identifier for a billing event"
        tests:
          - unique
          - not_null
      - name: user_id
        description: "ID of the user associated with the billing event"
      - name: event_type
        description: "Type of billing event"
      - name: amount
        description: "Amount associated with the billing event"
      - name: event_date
        description: "Date of the billing event"
      - name: load_timestamp
        description: "Timestamp when the data was loaded"
      - name: update_timestamp
        description: "Timestamp when the data was last updated"
      - name: source_system
        description: "Source system of the data"
