version: 2

sources:
  - name: raw
    database: raw
    schema: public
    tables:
      - name: users
      - name: meetings
      - name: participants
      - name: feature_usage
      - name: webinars
      - name: support_tickets
      - name: licenses
      - name: billing_events
