version: 2

sources:
  - name: raw
    database: raw
    schema: public
    tables:
      - name: users
        description: Raw users data from Zoom platform
        columns:
          - name: user_id
            description: Unique identifier for a user
          - name: user_name
            description: Name of the user
          - name: email
            description: Email address of the user
          - name: company
            description: Company the user belongs to
          - name: plan_type
            description: Type of plan the user has
          - name: load_timestamp
            description: Timestamp when the record was loaded
          - name: update_timestamp
            description: Timestamp when the record was last updated
          - name: source_system
            description: Source system of the data

      - name: meetings
        description: Raw meetings data from Zoom platform
        columns:
          - name: meeting_id
            description: Unique identifier for a meeting
          - name: host_id
            description: ID of the user hosting the meeting
          - name: meeting_topic
            description: Topic of the meeting
          - name: start_time
            description: Start time of the meeting
          - name: end_time
            description: End time of the meeting
          - name: duration_minutes
            description: Duration of the meeting in minutes
          - name: load_timestamp
            description: Timestamp when the record was loaded
          - name: update_timestamp
            description: Timestamp when the record was last updated
          - name: source_system
            description: Source system of the data

      - name: participants
        description: Raw participants data from Zoom platform
        columns:
          - name: participant_id
            description: Unique identifier for a participant
          - name: meeting_id
            description: ID of the meeting the participant attended
          - name: user_id
            description: ID of the user who participated
          - name: join_time
            description: Time when the participant joined the meeting
          - name: leave_time
            description: Time when the participant left the meeting
          - name: load_timestamp
            description: Timestamp when the record was loaded
          - name: update_timestamp
            description: Timestamp when the record was last updated
          - name: source_system
            description: Source system of the data

      - name: feature_usage
        description: Raw feature usage data from Zoom platform
        columns:
          - name: usage_id
            description: Unique identifier for a feature usage record
          - name: meeting_id
            description: ID of the meeting where the feature was used
          - name: feature_name
            description: Name of the feature used
          - name: usage_count
            description: Number of times the feature was used
          - name: usage_date
            description: Date when the feature was used
          - name: load_timestamp
            description: Timestamp when the record was loaded
          - name: update_timestamp
            description: Timestamp when the record was last updated
          - name: source_system
            description: Source system of the data

      - name: webinars
        description: Raw webinars data from Zoom platform
        columns:
          - name: webinar_id
            description: Unique identifier for a webinar
          - name: host_id
            description: ID of the user hosting the webinar
          - name: webinar_topic
            description: Topic of the webinar
          - name: start_time
            description: Start time of the webinar
          - name: end_time
            description: End time of the webinar
          - name: registrants
            description: Number of registrants for the webinar
          - name: load_timestamp
            description: Timestamp when the record was loaded
          - name: update_timestamp
            description: Timestamp when the record was last updated
          - name: source_system
            description: Source system of the data

      - name: support_tickets
        description: Raw support tickets data from Zoom platform
        columns:
          - name: ticket_id
            description: Unique identifier for a support ticket
          - name: user_id
            description: ID of the user who created the ticket
          - name: ticket_type
            description: Type of the support ticket
          - name: resolution_status
            description: Status of the ticket resolution
          - name: open_date
            description: Date when the ticket was opened
          - name: load_timestamp
            description: Timestamp when the record was loaded
          - name: update_timestamp
            description: Timestamp when the record was last updated
          - name: source_system
            description: Source system of the data

      - name: licenses
        description: Raw licenses data from Zoom platform
        columns:
          - name: license_id
            description: Unique identifier for a license
          - name: license_type
            description: Type of the license
          - name: assigned_to_user_id
            description: ID of the user the license is assigned to
          - name: start_date
            description: Start date of the license
          - name: end_date
            description: End date of the license
          - name: load_timestamp
            description: Timestamp when the record was loaded
          - name: update_timestamp
            description: Timestamp when the record was last updated
          - name: source_system
            description: Source system of the data

      - name: billing_events
        description: Raw billing events data from Zoom platform
        columns:
          - name: event_id
            description: Unique identifier for a billing event
          - name: user_id
            description: ID of the user associated with the billing event
          - name: event_type
            description: Type of the billing event
          - name: amount
            description: Amount associated with the billing event
          - name: event_date
            description: Date of the billing event
          - name: load_timestamp
            description: Timestamp when the record was loaded
          - name: update_timestamp
            description: Timestamp when the record was last updated
          - name: source_system
            description: Source system of the data
